# Generated by Django 3.1 on 2021-02-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourwatc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='biz_email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
